# Generated by Django 6.0.3 on 2026-04-01 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', 'Создан'), ('updated', 'Обновлён'), ('status_changed', 'Статус изменён'), ('confirmed', 'Подтверждён'), ('canceled', 'Отменён'), ('deleted', 'Удалён')], max_length=30, verbose_name='Тип изменения')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Изменил сотрудник')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История заказа',
                'verbose_name_plural': 'История заказов',
                'ordering': ['-created_at'],
            },
        ),
    ]
